apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-services
spec:
  ingressClassName: traefik
  rules:
  - host: keycloak.luxdomain.work
    http:
      paths:
      - backend:
          service:
            name: keycloak
            port:
              number: 8080
        path: /
        pathType: Prefix
  - host: portainer.luxdomain.work
    http:
      paths:
      - backend:
          service:
            name: portainer
            port:
              number: 9000
        path: /
        pathType: Prefix
  - host: longhorn.luxdomain.work
    http:
      paths:
      - backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: pgadmin.luxdomain.work
    http:
      paths:
      - backend:
          service:
            name: pgadmin
            port:
              number: 80
        path: /
        pathType: Prefix
