  # RabbitMQ Admin Credentials
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: lunarflow
type: Opaque
stringData:
  admin-username: admin
  admin-password: supersecretpassword
---
# Database (Postgres) and PGAdmin Credentials
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
  namespace: lunarflow
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: your-postgres-password
  PGADMIN_EMAIL: admin@localhost.local
  PGADMIN_PASSWORD: your-pgadmin-password
---
# Lunarflow Configurations
apiVersion: v1
kind: ConfigMap
metadata:
  name: lunarflow-config
  namespace: lunarflow
data:
  #Ticket API Configurations
  TICKETAPI_GITLAB_SERVER: https://gitlab.com/
  TICKETAPI_GITLAB_PROJECT: thijs.haker/lunarflow
  # Frontend Configurations
  FRONTEND_HOSTNAME: "http://frontend.luxdomain.lan"
  FRONTEND_NODE_ENV: "development"
  FRONTEND_API_URL: "http://ticket-api.luxdomain.lan"
  FRONTEND_CONTENT_API_URL: "http://content-api.luxdomain.lan"
  NEXTJS_URL: "https://lunarflow.luxdomain.work"
  # Keycloak Configurations
  QUARKUS_OIDC_AUTH_SERVER_URL: "https://keycloak.luxdomain.work/realms/eclipse"
  QUARKUS_OIDC_CLIENT_ID: lunarflow
---
# Lunarflow Secrets
apiVersion: v1
kind: Secret
metadata:
  name: lunarflow-secrets
  namespace: lunarflow
type: Opaque
stringData:
  # GitLab Token for Ticket API
  TICKETAPI_GITLAB_TOKEN: glpat-0000
  # Keycloak Client Secret
  QUARKUS_OIDC_CREDENTIALS_SECRET: your-keycloak-client-secret