  # RabbitMQ Admin Credentials
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: lunarflow
type: Opaque
stringData:
  # RabbitMQ Credentials
  admin-username: admin
  admin-password: supersecretpassword
---
# Database (Postgres) and PGAdmin Credentials
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
  namespace: lunarflow
stringData:
  # Postgres Credentials
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: your-postgres-password
  # PGAdmin Credentials
  PGADMIN_EMAIL: admin@localhost.local
  PGADMIN_PASSWORD: your-pgadmin-password
---
# Lunarflow Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: lunarflow-config
  namespace: lunarflow
data:
  #Ticket API Configuration
  TICKETAPI_GITLAB_SERVER: https://gitlab.com/
  TICKETAPI_GITLAB_PROJECT: thijs.haker/lunarflow
  # Keycloak Configuration
  QUARKUS_OIDC_AUTH_SERVER_URL: "https://keycloak.luxdomain.work/realms/eclipse"
  QUARKUS_OIDC_CLIENT_ID: lunarflow
---
# Lunarflow Secrets
apiVersion: v1          
kind: Secret
metadata:
  name: lunarflow-secrets
  namespace: lunarflow
type: Opaque
stringData:
  # GitLab Token for Ticket API
  TICKETAPI_GITLAB_TOKEN: glpat-0000
  # Keycloak Client Secret
  QUARKUS_OIDC_CREDENTIALS_SECRET: your-keycloak-client-secret