# Lunarflow Database Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: lunarflow
data:
  # PostgreSQL settings
  postgres-version: "15"
  postgres-storage-size: "8Gi"

  # pgAdmin settings
  pgadmin-storage-size: "1Gi"
  pgadmin-allowed-domains: "['local', 'localhost']"
---
  # RabbitMQ Admin Credentials
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: lunarflow
type: Opaque
stringData:
  admin-username: admin
  admin-password: supersecretpassword
---
# Database (Postgres) and PGAdmin Credentials
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
  namespace: lunarflow
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: your-postgres-password
  PGADMIN_EMAIL: admin@localhost.local
  PGADMIN_PASSWORD: your-pgadmin-password
---
# Lunarflow Configurations
apiVersion: v1
kind: ConfigMap
metadata:
  name: lunarflow-config
  namespace: lunarflow
data:
  TICKETAPI_GITLAB_PROJECT: thijs.haker/lunarflow
  TICKETAPI_GITLAB_SERVER: https://gitlab.com/
  FRONTEND_HOSTNAME: "0.0.0.0"
  FRONTEND_NODE_ENV: "development"
  FRONTEND_API_URL: "http://ticket-api.luxdomain.lan"
  FRONTEND_CONTENT_API_URL: "http://content-api.luxdomain.lan"
---
# Lunarflow Secrets
apiVersion: v1
kind: Secret
metadata:
  name: lunarflow-secrets
  namespace: lunarflow
type: Opaque
stringData:
  TICKETAPI_GITLAB_TOKEN: glpat-0000