# RabbitMQ Admin Credentials
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: lunarflow
type: Opaque
stringData:
  admin-username: admin
  admin-password: supersecretpassword
---
# Database (Postgres) and PGAdmin Credentials
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
  namespace: lunarflow
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: your-postgres-password
  PGADMIN_EMAIL: admin@localhost.local
  PGADMIN_PASSWORD: your-pgadmin-password