apiVersion: v1
kind: ServiceAccount
metadata:
  name: quarkus-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quarkus-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quarkus-secret-reader-binding
subjects:
  - kind: ServiceAccount
    name: quarkus-app
roleRef:
  kind: Role
  name: quarkus-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
spec:
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      serviceAccountName: quarkus-app
      containers:
      - name: content-api
        image: ghcr.io/fontys-lunarflow/content_api:master
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1024Mi"
            cpu: "2"
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: content-service
spec:
  selector:
    app: content-api
  ports:
  - port: 8080
    targetPort: http
