apiVersion: v1
kind: ConfigMap
metadata:
  name: lunarflow-config
  namespace: lunarflow
data:
  TICKETAPI_GITLAB_PROJECT: org/team/project
  TICKETAPI_GITLAB_SERVER: https://gitlab.com/

---
apiVersion: v1
kind: Secret
metadata:
  name: lunarflow-secrets
  namespace: lunarflow
type: Opaque
stringData:
  TICKETAPI_GITLAB_TOKEN: gl-0000